spring:
  mail:
    host: smtp.gmail.com
    password: Vineeth@2496
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    username: vineetharmoori2496@gmail.com
